# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-28 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='creation_date',
            field=models.DateField(auto_now=True),
        ),
    ]
