# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-29 01:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190428_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='creation_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='inventory_products',
            name='creation_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='creation_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='type_id',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='status',
        ),
        migrations.DeleteModel(
            name='type',
        ),
    ]
